# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\script\test-gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Inference import inference


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.predictButton = QtWidgets.QPushButton(self.centralwidget)
        self.predictButton.setGeometry(QtCore.QRect(240, 300, 341, 21))
        self.predictButton.setObjectName("predictButton")
        self.predictButton.clicked.connect(self.test)

        self.selectImButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectImButton.setGeometry(QtCore.QRect(240, 10, 331, 21))
        self.selectImButton.setObjectName("selectImButton")
        self.selectImButton.clicked.connect(self.setImage)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 350, 47, 13))
        self.label.setObjectName("label")
        self.resultValue = QtWidgets.QLabel(self.centralwidget)
        self.resultValue.setGeometry(QtCore.QRect(310, 350, 47, 13))
        self.resultValue.setObjectName("resultValue")
        self.ImageFrame = QtWidgets.QLabel(self.centralwidget)
        self.ImageFrame.setGeometry(QtCore.QRect(240, 50, 331, 221))
        self.ImageFrame.setObjectName("ImageFrame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.predictButton.setText(_translate("MainWindow", "Predict"))
        self.selectImButton.setText(_translate("MainWindow", "Select Image"))
        self.label.setText(_translate("MainWindow", "Result"))
        self.resultValue.setText(_translate("MainWindow", "Res:"))
        self.ImageFrame.setText(_translate("MainWindow", "TextLabel"))

    def test(self):
        value = inference("Alexnet",self.fileName)
        self.resultValue.setText(value)
        

    def setImage(self):
        self.fileName, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Select Image", "", "Image Files (*.png *.jpg *jpeg *.bmp);;All Files (*)") # Ask for file
        if self.fileName: # If the user gives a file
            image = QtGui.QPixmap(self.fileName) # Setup pixmap with the provided image
            image = image.scaled(self.ImageFrame.width(), self.ImageFrame.height(), QtCore.Qt.KeepAspectRatio) # Scale pixmap
           
            self.ImageFrame.setPixmap(image) # Set the pixmap onto the label
           
        else:
            self.label.setPixmap(QtGui.QPixmap())
            self.submitButton.setEnabled(False)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
